#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/* sdkconfig.h defines CONFIG_* macros from menuconfig. MUST be included
 * before any #ifdef CONFIG_* check below. Generated by the build system
 * into build/config/sdkconfig.h. */
#include "sdkconfig.h"

#include <stdint.h>
#include <stdbool.h>

/*
 * ESP8266 WiFi Microphone — Board Configuration (thin aggregator)
 *
 * Audio pipeline: INMP441 (I2S) -> TPF dither -> IMA ADPCM (DVI4) -> UDP/TCP/RawTX
 *
 * Runtime-tunable settings (sample rate, channels, I2S bits, comm format)
 * live in NVS and are editable via AT commands. Kconfig provides compile-time
 * defaults that boot uses when NVS is empty.
 *
 * R3-C: this file was split into focused sub-headers. It now serves as a
 * thin aggregator that pulls in all the sub-headers and performs cross-
 * validation #error checks. Existing #include "board_config.h" sites
 * continue to work unchanged.
 */

/* Thin aggregator — all config in focused sub-headers */
#include "board_audio.h"
#include "board_wifi.h"
#include "board_network.h"
#include "board_tasks.h"
#include "board_battery.h"
#include "board_protocol.h"

/* ====================================================================
 *  Cross-validation checks (M31, M32)
 * ====================================================================
 * These MUST live at the END of this file, after all macros they reference
 * have been defined (via the sub-headers above) — earlier placement caused
 * #error to fire on still-undefined macros (preprocessor treats undefined
 * identifiers as 0). FIX (M31/M32): see FIXES.md */

/* M31: STREAM_STOP_TIMEOUT_*_MS must be > corresponding send timeout,
 * otherwise force-deleting a task blocked in sendto()/send() corrupts lwIP
 * state -> orphaned mutex -> deadlock on next start_streaming(). */
#if (STREAM_STOP_TIMEOUT_UDP_MS <= UDP_SEND_TIMEOUT_MS)
#error "STREAM_STOP_TIMEOUT_UDP_MS must be > UDP_SEND_TIMEOUT_MS"
#endif

#if (STREAM_STOP_TIMEOUT_UDP_MS <= UDP_RECEIVE_TIMEOUT_MS)
#error "STREAM_STOP_TIMEOUT_UDP_MS must be > UDP_RECEIVE_TIMEOUT_MS"
#endif

#if (STREAM_STOP_TIMEOUT_TCP_MS <= (TCP_SEND_TIMEOUT_MS * (TCP_EAGAIN_MAX_RETRIES + 1)))
#error "STREAM_STOP_TIMEOUT_TCP_MS must be > (TCP_SEND_TIMEOUT_MS * (TCP_EAGAIN_MAX_RETRIES + 1)) — total send time exceeds stop timeout"
#endif

/* F3-A HIGH #1: TCP_FRAME_SEND_DEADLINE_MS bounds the total wall-clock time
 * for sending one complete frame (partial sends + EAGAIN retries combined).
 * Slow-reader clients that do partial reads bypass the EAGAIN counter
 * (eagain_retries resets to 0 on each partial send), so the per-frame
 * deadline — not just the per-send timeout — must be under the stop timeout
 * to prevent stop_streaming() force-deleting the TX task mid-send. */
#if (STREAM_STOP_TIMEOUT_TCP_MS <= TCP_FRAME_SEND_DEADLINE_MS)
#error "STREAM_STOP_TIMEOUT_TCP_MS must be > TCP_FRAME_SEND_DEADLINE_MS — total send time exceeds stop timeout"
#endif

/* M32: BATT_START_MV must be > BATT_CRITICAL_MV (otherwise boot deep-sleep
 * threshold is inverted — device would deep-sleep at boot with OK battery). */
#if BATTERY_ENABLED
#if (BATT_START_MV <= BATT_CRITICAL_MV)
#error "BATT_START_MV must be > BATT_CRITICAL_MV"
#endif
/* FIX (AUDIT-H19): see FIXES.md — BATT_CRITICAL_MV >= 4200 underflows battery_get_percent(). */
#if (BATT_CRITICAL_MV >= 4200)
#error "BATT_CRITICAL_MV must be < 4200"
#endif
#endif

#endif /* BOARD_CONFIG_H */
