#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/* sdkconfig.h defines CONFIG_* macros from menuconfig. MUST be included
 * before any #ifdef CONFIG_* checks below, otherwise fallback defaults
 * silently override menuconfig settings. Generated by the build system
 * into build/config/sdkconfig.h. */
#include "sdkconfig.h"

#include <stdint.h>
#include <stdbool.h>

/*
 * ESP8266 WiFi Microphone - Board Configuration
 *
 * Audio pipeline:
 *   INMP441 (I2S) -> TPDF dither -> IMA ADPCM (DVI4) -> UDP
 *
 * All runtime-tunable settings (sample rate, channels, I2S bits, comm format)
 * live in NVS and are editable via AT commands. Kconfig provides compile-time
 * defaults that boot uses when NVS is empty.
 *
 * I2S PINS - fixed in silicon (ESP8266 TRM):
 *   I2SI_DATA = GPIO12 (MTDI)
 *   I2SI_BCK  = GPIO13 (MTCK)
 *   I2SI_WS   = GPIO14 (MTMS)
 *
 * INMP441 wiring:
 *   SCK    -> GPIO13 (BCK)
 *   SD     -> GPIO12 (DATA) + 100k pulldown to GND
 *   WS     -> GPIO14 (WS)
 *   L/R    -> GND (left channel)
 *   VDD    -> 3.3V + 0.1uF decoupling
 *   CHIPEN -> 3.3V
 */

/* ====================================================================
 *  Audio parameters - configured via Kconfig (menuconfig)
 * ==================================================================== */

#ifdef CONFIG_STREAMER_AUDIO_SAMPLE_RATE
#define AUDIO_SAMPLE_RATE   CONFIG_STREAMER_AUDIO_SAMPLE_RATE
#else
#define AUDIO_SAMPLE_RATE   16000
#endif

#define AUDIO_SAMPLE_RATE_DEFAULT  AUDIO_SAMPLE_RATE

/* Valid sample rates (for AT+RATE validation) */
#define SAMPLE_RATE_COUNT  7
static const uint32_t VALID_SAMPLE_RATES[SAMPLE_RATE_COUNT] = {
    8000, 11025, 16000, 22050, 32000, 44100, 48000
};

/* Sample rate enum for packet header (RTP payload format).
 *   0=8000, 1=11025, 2=16000, 3=22050, 4=32000, 5=44100, 6=48000 */
static inline uint8_t sample_rate_to_enum(uint32_t rate)
{
    for (int i = 0; i < SAMPLE_RATE_COUNT; i++) {
        if (VALID_SAMPLE_RATES[i] == rate) return (uint8_t)i;
    }
    return 2;  /* fallback: 16000 */
}

static inline bool sample_rate_is_valid(uint32_t rate)
{
    for (int i = 0; i < SAMPLE_RATE_COUNT; i++) {
        if (VALID_SAMPLE_RATES[i] == rate) return true;
    }
    return false;
}

/* I2S bits per sample - 16 or 24 */
#ifdef CONFIG_STREAMER_I2S_BITS_PER_SAMPLE
#define I2S_BITS_PER_SAMPLE CONFIG_STREAMER_I2S_BITS_PER_SAMPLE
#else
#define I2S_BITS_PER_SAMPLE 24
#endif

/* Digital gain multiplier (0-64). Applied to 24-bit sample before TPDF
 * dither, only in 24-bit mode. Compensates for INMP441's low sensitivity
 * (-26 dBFS @ 94 dB SPL). 0 = bypass (no gain). 32 = +30 dB (default).
 * Adjustable at runtime via AT+GAIN. Used only when AGC is off. */
#ifdef CONFIG_STREAMER_AUDIO_GAIN
#define AUDIO_GAIN_DEFAULT CONFIG_STREAMER_AUDIO_GAIN
#else
#define AUDIO_GAIN_DEFAULT 32
#endif

/* AGC (Automatic Gain Control) - preset modes.
 *   0 = OFF: use fixed gain (AUDIO_GAIN_DEFAULT)
 *   1 = LOW:    attack=50, release=10 - slow, minimal hiss (quiet room)
 *   2 = MEDIUM: attack=75, release=20 - balanced (default)
 *   3 = HIGH:   attack=90, release=50 - fast reaction (dynamic source, more hiss)
 *
 * When mode != 0, AGC overrides fixed gain. Target -18 dBFS, max gain 64x,
 * noise gate at -42 dBFS. Works for both 16 and 24-bit.
 * Adjustable at runtime via AT+AGC=0|1|2|3. */
#ifdef CONFIG_STREAMER_AGC_MODE
#define AUDIO_AGC_DEFAULT CONFIG_STREAMER_AGC_MODE
#else
#define AUDIO_AGC_DEFAULT 2   /* MEDIUM */
#endif

#define AGC_MODE_OFF    0
#define AGC_MODE_LOW    1
#define AGC_MODE_MEDIUM 2
#define AGC_MODE_HIGH   3

/* AGC preset parameters: attack and release speeds (1-100, % per frame).
 * Attack: how fast gain DROPS when signal is loud (envelope rising).
 * Release: how fast gain RISES when signal is quiet (envelope falling).
 * Lower release = less noise hiss but slower recovery. */
#define AGC_LOW_ATTACK    50
#define AGC_LOW_RELEASE   10
#define AGC_MED_ATTACK    75
#define AGC_MED_RELEASE   20
#define AGC_HIGH_ATTACK   90
#define AGC_HIGH_RELEASE  50

/* I2S communication format
 *   0 = Philips I2S (msb_shift=1) - standard, INMP441
 *   1 = LSB / Left-justified (msb_shift=0) */
#ifdef CONFIG_STREAMER_I2S_COMM_FORMAT
#define I2S_COMM_FORMAT_CFG CONFIG_STREAMER_I2S_COMM_FORMAT
#else
#define I2S_COMM_FORMAT_CFG 0
#endif

/* Frame duration (ms) - COMPUTED at runtime from sample_rate, channels, bits.
 * See i2s_capture_compute_frame_ms(). Guarantees:
 *   - samples_per_frame is even (ADPCM packs 2 samples/byte)
 *   - samples_per_frame/4 >= 32 (SDK DMA minimum)
 *   - UDP packet <= 1400 bytes (MTU safe, codec & bits aware)
 *   - If rawtx_mode: air_time/sec <= 0.95 (Raw TX throughput limit) */
uint32_t i2s_capture_compute_frame_ms(uint32_t sample_rate, int channels,
                                       int codec_mode, int bits_per_sample);

/* Number of audio channels - configured via Kconfig
 *   1 = mono, 2 = stereo */
#ifdef CONFIG_STREAMER_AUDIO_CHANNELS
#define AUDIO_CHANNELS      CONFIG_STREAMER_AUDIO_CHANNELS
#else
#define AUDIO_CHANNELS      1
#endif

/* I2S channel format (matches ESP8266 RTOS SDK enum)
 *   0 = I2S_CHANNEL_FMT_RIGHT_LEFT  (stereo)
 *   1 = I2S_CHANNEL_FMT_ALL_RIGHT
 *   2 = I2S_CHANNEL_FMT_ALL_LEFT
 *   3 = I2S_CHANNEL_FMT_ONLY_RIGHT  (mono right)
 *   4 = I2S_CHANNEL_FMT_ONLY_LEFT   (mono left) */
#ifdef CONFIG_STREAMER_I2S_CHANNEL_FORMAT
#define I2S_CHANNEL_FORMAT  CONFIG_STREAMER_I2S_CHANNEL_FORMAT
#else
#define I2S_CHANNEL_FORMAT  4   /* ONLY_LEFT */
#endif

/* ADPCM = 4 bits/sample x channels */
#define AUDIO_BITRATE       (AUDIO_SAMPLE_RATE * 4 * AUDIO_CHANNELS)
#define CODEC_ID_ADPCM      5       /* DVI4 IMA ADPCM */
#define CODEC_ID_PCM        6       /* Raw 16/24-bit signed PCM */

/* Audio codec selection (0 = ADPCM, 1 = PCM).
 * ADPCM: 4 bits/sample, low bandwidth (32 kbps @ 16kHz).
 *        Requires encoding, but only ~10% CPU on ESP8266.
 * PCM:   Raw 16-bit or 24-bit signed PCM, no compression.
 *        High bandwidth (1536 kbps @ 48kHz/16-bit/stereo).
 *        Zero CPU overhead for encoding, but exceeds UDP MTU at
 *        high sample rates - frame_ms is auto-reduced to fit.
 * Adjustable at runtime via AT+CODEC=0|1 (saved, applies on next stream). */
#define CODEC_MODE_ADPCM    0
#define CODEC_MODE_PCM      1

#ifdef CONFIG_STREAMER_AUDIO_CODEC
#define AUDIO_CODEC_DEFAULT CONFIG_STREAMER_AUDIO_CODEC
#else
#define AUDIO_CODEC_DEFAULT CODEC_MODE_ADPCM
#endif

/* WiFi transmission mode (0=UDP via router, 1=Raw 802.11 TX broadcast).
 * Raw TX mode bypasses the TCP/IP stack and sends raw 802.11 data frames
 * directly into the air on a fixed channel. No router needed.
 * Receiver must be in Monitor Mode. */
#define RAWTX_MODE_UDP     0   /* used by RAWTX_MODE_DEFAULT */

#ifdef CONFIG_STREAMER_RAWSWITCH
#define RAWTX_MODE_DEFAULT CONFIG_STREAMER_RAWSWITCH
#else
#define RAWTX_MODE_DEFAULT RAWTX_MODE_UDP
#endif

#ifdef CONFIG_STREAMER_RAWTX_CHANNEL
#define RAWTX_CHANNEL_DEFAULT CONFIG_STREAMER_RAWTX_CHANNEL
#else
#define RAWTX_CHANNEL_DEFAULT 1
#endif

/* Firmware version - single source of truth. */
#define FIRMWARE_VERSION    "v2.0"

/* samples_per_frame and adpcm_frame_bytes are computed at runtime in
 * start_streaming() from frame_ms - no compile-time constants. */

/* ====================================================================
 *  WiFi defaults - configured via Kconfig, overridable via AT+WIFI
 * ==================================================================== */

#ifdef CONFIG_STREAMER_WIFI_SSID
#define WIFI_SSID_DEFAULT        CONFIG_STREAMER_WIFI_SSID
#else
#define WIFI_SSID_DEFAULT        "YOUR_WIFI_SSID"
#endif

#ifdef CONFIG_STREAMER_WIFI_PASSWORD
#define WIFI_PASSWORD_DEFAULT    CONFIG_STREAMER_WIFI_PASSWORD
#else
#define WIFI_PASSWORD_DEFAULT    "12345678"
#endif

#ifdef CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#define WIFI_TX_POWER_DEFAULT    CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#define WIFI_TX_POWER_MAX        CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#else
#define WIFI_TX_POWER_DEFAULT    20
#define WIFI_TX_POWER_MAX        20
#endif
#define WIFI_TX_POWER_MIN        0

#ifdef CONFIG_STREAMER_WIFI_HOSTNAME
#define WIFI_HOSTNAME_DEFAULT    CONFIG_STREAMER_WIFI_HOSTNAME
#else
#define WIFI_HOSTNAME_DEFAULT    "esp-streamer"
#endif

#ifdef CONFIG_STREAMER_WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS  CONFIG_STREAMER_WIFI_CONNECT_TIMEOUT_MS
#else
#define WIFI_CONNECT_TIMEOUT_MS  15000
#endif

#ifdef CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MIN_MS
#define WIFI_RECONNECT_BACKOFF_MIN_MS  CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MIN_MS
#else
#define WIFI_RECONNECT_BACKOFF_MIN_MS  1000
#endif

#ifdef CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MAX_MS
#define WIFI_RECONNECT_BACKOFF_MAX_MS  CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MAX_MS
#else
#define WIFI_RECONNECT_BACKOFF_MAX_MS  30000
#endif

/* ====================================================================
 *  Service Port (EASSP) - configured via Kconfig
 * ==================================================================== */

#ifdef CONFIG_STREAMER_SVC_PORT
#define SVC_PORT_DEFAULT         CONFIG_STREAMER_SVC_PORT
#else
#define SVC_PORT_DEFAULT         3950
#endif

#ifdef CONFIG_STREAMER_SVC_WATCHDOG_TIMEOUT_MS
#define SVC_WATCHDOG_TIMEOUT_MS  CONFIG_STREAMER_SVC_WATCHDOG_TIMEOUT_MS
#else
#define SVC_WATCHDOG_TIMEOUT_MS  15000
#endif

#ifdef CONFIG_STREAMER_SVC_INFO_INTERVAL_MS
#define SVC_INFO_INTERVAL_MS     CONFIG_STREAMER_SVC_INFO_INTERVAL_MS
#else
#define SVC_INFO_INTERVAL_MS     1000
#endif

/* Broadcast announcements - controlled by Kconfig STREAMER_SVC_ANNOUNCE_ENABLED. */
#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_ENABLED
#define SVC_ANNOUNCE_ENABLED     1
#else
#define SVC_ANNOUNCE_ENABLED     0
#endif

#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_MIN_MS
#define SVC_ANNOUNCE_MIN_MS      CONFIG_STREAMER_SVC_ANNOUNCE_MIN_MS
#else
#define SVC_ANNOUNCE_MIN_MS      1000
#endif

#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_MAX_MS
#define SVC_ANNOUNCE_MAX_MS      CONFIG_STREAMER_SVC_ANNOUNCE_MAX_MS
#else
#define SVC_ANNOUNCE_MAX_MS      5000
#endif

#ifdef CONFIG_STREAMER_SVC_RECV_BUF_SIZE
#define SVC_RECV_BUF_SIZE        CONFIG_STREAMER_SVC_RECV_BUF_SIZE
#else
#define SVC_RECV_BUF_SIZE        256
#endif

#ifdef CONFIG_STREAMER_SVC_RECONFIGURE_STOP_TIMEOUT_MS
#define SVC_RECONFIGURE_STOP_TIMEOUT_MS  CONFIG_STREAMER_SVC_RECONFIGURE_STOP_TIMEOUT_MS
#else
#define SVC_RECONFIGURE_STOP_TIMEOUT_MS  2000
#endif

/* ====================================================================
 *  Pipeline / Task Configuration
 * ==================================================================== */

#ifdef CONFIG_STREAMER_TASK_PRIO_I2S
#define TASK_PRIO_I2S       CONFIG_STREAMER_TASK_PRIO_I2S
#else
#define TASK_PRIO_I2S       5
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_ADPCM
#define TASK_PRIO_ADPCM     CONFIG_STREAMER_TASK_PRIO_ADPCM
#else
#define TASK_PRIO_ADPCM     3
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_UDP
#define TASK_PRIO_UDP       CONFIG_STREAMER_TASK_PRIO_UDP
#else
#define TASK_PRIO_UDP       2
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_AT
#define TASK_PRIO_AT        CONFIG_STREAMER_TASK_PRIO_AT
#else
#define TASK_PRIO_AT        1
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_SVC
#define TASK_PRIO_SVC       CONFIG_STREAMER_TASK_PRIO_SVC
#else
#define TASK_PRIO_SVC       2
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_I2S
#define TASK_STACK_I2S      CONFIG_STREAMER_TASK_STACK_I2S
#else
#define TASK_STACK_I2S      3584
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_ADPCM
#define TASK_STACK_ADPCM    CONFIG_STREAMER_TASK_STACK_ADPCM
#else
#define TASK_STACK_ADPCM    2560
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_UDP
#define TASK_STACK_UDP      CONFIG_STREAMER_TASK_STACK_UDP
#else
#define TASK_STACK_UDP      3072
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_AT
#define TASK_STACK_AT       CONFIG_STREAMER_TASK_STACK_AT
#else
#define TASK_STACK_AT       3584
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_SVC
#define TASK_STACK_SVC      CONFIG_STREAMER_TASK_STACK_SVC
#else
#define TASK_STACK_SVC      3584
#endif

/* PCM/ADPCM pool sizes are computed at runtime in start_streaming() from
 * free heap and frame_ms - see main.c. No compile-time setting needed. */

#ifdef CONFIG_STREAMER_STREAM_STOP_TIMEOUT_MS
#define STREAM_STOP_TIMEOUT_MS  CONFIG_STREAMER_STREAM_STOP_TIMEOUT_MS
#else
/* FIX (H1): Must be > UDP_SEND_TIMEOUT_MS (2000ms) so that stream_task_fn
 * blocked in sendto() has time to return. With 500ms, the task gets force-
 * deleted while inside lwIP sendto() -> corrupted state + orphaned mutex
 * -> deadlock on next start_streaming(). 3000ms gives a safe margin. */
#define STREAM_STOP_TIMEOUT_MS  3000
#endif

/* I2S DMA buffer dimensions are DERIVED from samples_per_frame at runtime
 * (see i2s_capture_init). One PCM frame = 4 DMA buffers, so each DMA
 * buffer fills in frame_ms/4. DMA buffer count gives ~256ms of headroom. */

/* ====================================================================
 *  AT Command Interface
 * ==================================================================== */

#ifdef CONFIG_STREAMER_AT_CMD_ENABLED
#define AT_CMD_ENABLED      1
#else
#define AT_CMD_ENABLED      0
#endif

#ifdef CONFIG_STREAMER_UART_BAUD_RATE
#define UART_BAUD_RATE      CONFIG_STREAMER_UART_BAUD_RATE
#else
#define UART_BAUD_RATE      115200
#endif

/* ====================================================================
 *  Network / UDP
 * ==================================================================== */

#ifdef CONFIG_STREAMER_UDP_SEND_TIMEOUT_MS
#define UDP_SEND_TIMEOUT_MS CONFIG_STREAMER_UDP_SEND_TIMEOUT_MS
#else
#define UDP_SEND_TIMEOUT_MS 2000
#endif

/* ====================================================================
 *  Battery Monitoring (optional, ported from ESP8285-WEBSERVER project)
 * ====================================================================
 *
 * ESP8266 has a single ADC channel (TOUT pin, ADC_READ_TOUT_MODE) which
 * measures 0-1V (10-bit, 0-1023). A voltage divider on the battery side
 * scales V_batt down to fit this 0-1V range.
 *
 * Example divider for Li-Ion (3.0-4.2V):
 *   R1=100k (to V_batt), R2=33k (to GND), TOUT at junction
 *   V_tout = V_batt * R2 / (R1 + R2) = V_batt * 33/133 = V_batt * 0.2481
 *   At V_batt=4.2V -> V_tout=1.042V (slightly clipped, OK)
 *   At V_batt=3.0V -> V_tout=0.744V
 *   RATIO = 1024 / 0.2481 ~ 5711 (calibration constant)
 *
 * Formula: V_batt_mV = (ADC_raw x RATIO) / 1024
 *
 * IMPORTANT: ESP8266 ADC is SHARED - if the I2S INMP441 mic uses GPIO12
 * (data), the ADC TOUT pin (separate from GPIOs) remains available.
 * Verify that your hardware routes V_batt divider to the TOUT pin, not
 * to a GPIO used by I2S.
 */

#ifdef CONFIG_STREAMER_BATTERY_ENABLED
#define BATTERY_ENABLED 1
#else
#define BATTERY_ENABLED 0
#endif

#ifndef CONFIG_STREAMER_BATT_CRITICAL_MV
#define BATT_CRITICAL_MV  3700   /* below -> deep sleep */
#else
#define BATT_CRITICAL_MV  CONFIG_STREAMER_BATT_CRITICAL_MV
#endif

#ifndef CONFIG_STREAMER_BATT_START_MV
#define BATT_START_MV     3900   /* below on boot -> don't start */
#else
#define BATT_START_MV     CONFIG_STREAMER_BATT_START_MV
#endif

#ifndef CONFIG_STREAMER_BATT_BAD_MV
#define BATT_BAD_MV       2500   /* below -> reading is invalid */
#else
#define BATT_BAD_MV       CONFIG_STREAMER_BATT_BAD_MV
#endif

#ifndef CONFIG_STREAMER_BATT_DIVIDER_RATIO
#define BATT_DIVIDER_RATIO 5711  /* R1=100k, R2=33k -> 5711 */
#else
#define BATT_DIVIDER_RATIO CONFIG_STREAMER_BATT_DIVIDER_RATIO
#endif

#ifndef CONFIG_STREAMER_BATT_ADC_SAMPLES
#define BATT_ADC_SAMPLES  15
#else
#define BATT_ADC_SAMPLES  CONFIG_STREAMER_BATT_ADC_SAMPLES
#endif

#ifndef CONFIG_STREAMER_BATT_ADC_DELAY_MS
#define BATT_ADC_DELAY_MS 50
#else
#define BATT_ADC_DELAY_MS CONFIG_STREAMER_BATT_ADC_DELAY_MS
#endif

#ifndef CONFIG_STREAMER_BATT_CHECK_MIN
#define BATT_CHECK_MIN    1      /* check every N minutes during operation */
#else
#define BATT_CHECK_MIN    CONFIG_STREAMER_BATT_CHECK_MIN
#endif

#ifndef CONFIG_STREAMER_BATT_SLEEP_MIN
#define BATT_SLEEP_MIN    30     /* deep sleep duration on critical battery */
#else
#define BATT_SLEEP_MIN    CONFIG_STREAMER_BATT_SLEEP_MIN
#endif

#ifndef CONFIG_STREAMER_BATT_TASK_STACK
#define BATT_TASK_STACK   1024
#else
#define BATT_TASK_STACK   CONFIG_STREAMER_BATT_TASK_STACK
#endif

#ifndef CONFIG_STREAMER_BATT_TASK_PRIO
#define BATT_TASK_PRIO    3
#else
#define BATT_TASK_PRIO    CONFIG_STREAMER_BATT_TASK_PRIO
#endif

/* ====================================================================
 *  Fixed Protocol Constants (NOT configurable)
 * ==================================================================== */

/*
 * UDP packet header (16 bytes, packed):
 *   seq_num(2) + timestamp_ms(4) + codec(1) +
 *   sample_rate_enum(1) + channels(1) + frame_ms(1) +
 *   bitrate(4) + flags(2)
 */
#define PKT_HDR_SIZE        16
#define DVI4_HEADER_SIZE    4        /* predict(2) + index(1) + reserved(1) */

#endif /* BOARD_CONFIG_H */
