#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/* sdkconfig.h defines CONFIG_* macros from menuconfig. MUST be included
 * before any #ifdef CONFIG_* checks below, otherwise fallback defaults
 * silently override menuconfig settings. Generated by the build system
 * into build/config/sdkconfig.h. */
#include "sdkconfig.h"

#include <stdint.h>
#include <stdbool.h>

/*
 * ESP8266 WiFi Microphone - Board Configuration
 *
 * Audio pipeline:
 *   INMP441 (I2S) -> TPDF dither -> IMA ADPCM (DVI4) -> UDP
 *
 * All runtime-tunable settings (sample rate, channels, I2S bits, comm format)
 * live in NVS and are editable via AT commands. Kconfig provides compile-time
 * defaults that boot uses when NVS is empty.
 *
 * I2S PINS - fixed in silicon (ESP8266 TRM):
 *   I2SI_DATA = GPIO12 (MTDI)
 *   I2SI_BCK  = GPIO13 (MTCK)
 *   I2SI_WS   = GPIO14 (MTMS)
 *
 * INMP441 wiring:
 *   SCK    -> GPIO13 (BCK)
 *   SD     -> GPIO12 (DATA) + 100k pulldown to GND
 *   WS     -> GPIO14 (WS)
 *   L/R    -> GND (left channel)
 *   VDD    -> 3.3V + 0.1uF decoupling
 *   CHIPEN -> 3.3V
 */

/* ====================================================================
 *  Audio parameters - configured via Kconfig (menuconfig)
 * ==================================================================== */

#ifdef CONFIG_STREAMER_AUDIO_SAMPLE_RATE
#define AUDIO_SAMPLE_RATE   CONFIG_STREAMER_AUDIO_SAMPLE_RATE
#else
#define AUDIO_SAMPLE_RATE   16000
#endif

#define AUDIO_SAMPLE_RATE_DEFAULT  AUDIO_SAMPLE_RATE

/* Valid sample rates (for AT+RATE validation) */
#define SAMPLE_RATE_COUNT  7
static const uint32_t VALID_SAMPLE_RATES[SAMPLE_RATE_COUNT] = {
    8000, 11025, 16000, 22050, 32000, 44100, 48000
};

/* Sample rate enum for packet header (RTP payload format).
 *   0=8000, 1=11025, 2=16000, 3=22050, 4=32000, 5=44100, 6=48000 */
static inline uint8_t sample_rate_to_enum(uint32_t rate)
{
    for (int i = 0; i < SAMPLE_RATE_COUNT; i++) {
        if (VALID_SAMPLE_RATES[i] == rate) return (uint8_t)i;
    }
    return 2;  /* fallback: 16000 */
}

static inline bool sample_rate_is_valid(uint32_t rate)
{
    for (int i = 0; i < SAMPLE_RATE_COUNT; i++) {
        if (VALID_SAMPLE_RATES[i] == rate) return true;
    }
    return false;
}

/* I2S bits per sample - 16 or 24 */
#ifdef CONFIG_STREAMER_I2S_BITS_PER_SAMPLE
#define I2S_BITS_PER_SAMPLE CONFIG_STREAMER_I2S_BITS_PER_SAMPLE
#else
#define I2S_BITS_PER_SAMPLE 24
#endif

/* Digital gain multiplier (0-64). Applied to 24-bit sample before TPDF
 * dither, only in 24-bit mode. Compensates for INMP441's low sensitivity
 * (-26 dBFS @ 94 dB SPL). 0 = bypass (no gain). 32 = +30 dB (default).
 * Adjustable at runtime via AT+GAIN. Used only when AGC is off. */
#ifdef CONFIG_STREAMER_AUDIO_GAIN
#define AUDIO_GAIN_DEFAULT CONFIG_STREAMER_AUDIO_GAIN
#else
#define AUDIO_GAIN_DEFAULT 32
#endif

/* AGC (Automatic Gain Control) - preset modes.
 *   0 = OFF: use fixed gain (AUDIO_GAIN_DEFAULT)
 *   1 = LOW:    attack=50, release=10 - slow, minimal hiss (quiet room)
 *   2 = MEDIUM: attack=75, release=20 - balanced (default)
 *   3 = HIGH:   attack=90, release=50 - fast reaction (dynamic source, more hiss)
 *
 * When mode != 0, AGC overrides fixed gain. Target -18 dBFS, max gain 64x,
 * noise gate at -42 dBFS. Works for both 16 and 24-bit.
 * Adjustable at runtime via AT+AGC=0|1|2|3. */
#ifdef CONFIG_STREAMER_AGC_MODE
#define AUDIO_AGC_DEFAULT CONFIG_STREAMER_AGC_MODE
#else
#define AUDIO_AGC_DEFAULT 3   /* Voice Balanced */
#endif

/* AGC (Automatic Gain Control) — 9 presets, each with its own character.
 *
 * Parameters per preset:
 *   attack        — speed of gain DROP when signal is loud (% per frame, 1-100)
 *   release       — speed of gain RISE when signal is quiet (% per frame, 1-100)
 *   target_q16    — target output level in Q16.16 fixed-point
 *                   (level as fraction of full scale, scaled by 65536).
 *                   0 = use bit-depth default (-18 dBFS).
 *   noise_gate_q16 — below this level, gain = 1x (bypass). 0 = use default.
 *
 * Q16.16 encoding: value = level * 65536. Examples (level = 10^(dBFS/20)):
 *   -18 dBFS: level=0.1259, q16 =  8248   (bit-depth default)
 *   -15 dBFS: level=0.1778, q16 = 11658
 *   -12 dBFS: level=0.2512, q16 = 16463
 *    -6 dBFS: level=0.5012, q16 = 32846
 *   -48 dBFS: level=0.0040, q16 =   261
 *   -42 dBFS: level=0.0079, q16 =   521
 *   -36 dBFS: level=0.0158, q16 =  1039
 *   -30 dBFS: level=0.0316, q16 =  2073
 *   -60 dBFS: level=0.0010, q16 =    66
 *
 * i2s_capture.c converts q16 → raw sample value via:
 *   raw_target = (full_scale * target_q16) >> 16
 * which works for both 16-bit (full_scale=32768) and 24-bit (8388608).
 *
 * For 24-bit mode, the AGC operates in the 24-bit domain (max 8388607).
 * The same q16 values apply — the conversion handles bit depth. */
#define AGC_MODE_COUNT      9

#define AGC_MODE_OFF            0
#define AGC_MODE_STUDIO_SOFT    1
#define AGC_MODE_PODCAST        2
#define AGC_MODE_VOICE_BALANCED 3
#define AGC_MODE_VOICE_FAST     4
#define AGC_MODE_NOISY_ROOM     5
#define AGC_MODE_MUSIC          6
#define AGC_MODE_LIMITER        7
#define AGC_MODE_SURVEILLANCE   8

typedef struct {
    const char *name;
    uint8_t  attack;        /* % per frame, gain dropping (1-100) */
    uint8_t  release;       /* % per frame, gain rising (1-100) */
    int32_t  target_q16;    /* target level in Q16.16 (0 = use bit-depth default) */
    int32_t  noise_gate_q16;/* noise gate in Q16.16 (0 = use default) */
} agc_preset_t;

/* 16-bit equivalents for target/noise_gate (used when target_q16 = 0) */
#define AGC_TARGET_16BIT    (1 << 12)   /* -18 dBFS raw in 16-bit domain (4096) */
#define AGC_TARGET_24BIT    (1 << 20)   /* -18 dBFS raw in 24-bit domain (1048576) */
#define AGC_NOISE_GATE_DIV  64          /* noise gate = target / DIV (if preset has 0) */

static const agc_preset_t AGC_PRESETS[AGC_MODE_COUNT] = {
    /* 0: OFF — bypass, use fixed gain (AT+GAIN) */
    { "OFF",             0,   0,  0,        0 },

    /* 1: Studio Soft — very smooth, minimal pumping, for clean recordings.
     *   target=-18dBFS (0.126), gate=-48dBFS (0.004) */
    { "Studio Soft",    30,   5,  8248,     261 },

    /* 2: Podcast — smooth control for voice, moderate gate.
     *   target=-18dBFS, gate=-42dBFS (0.008) */
    { "Podcast",        50,  15,  8248,     521 },

    /* 3: Voice Balanced — current MEDIUM, good default for speech.
     *   target=-18dBFS, gate=-42dBFS */
    { "Voice Balanced", 75,  20,  8248,     521 },

    /* 4: Voice Fast — fast reaction for dynamic speech.
     *   target=-18dBFS, gate=-36dBFS (0.016) */
    { "Voice Fast",     90,  40,  8248,    1039 },

    /* 5: Noisy Room — high noise gate, cuts background noise.
     *   target=-15dBFS (0.178, slightly louder), gate=-30dBFS (0.032) */
    { "Noisy Room",     60,  25, 11658,    2073 },

    /* 6: Music — slow attack (don't compress transients), fast release.
     *   target=-12dBFS (0.251, preserves dynamics), gate=-60dBFS (0.001) */
    { "Music",          15,  60, 16463,      66 },

    /* 7: Limiter — only limits peaks, doesn't boost quiet signal.
     *   target=-6dBFS (0.501, high threshold), gate=-60dBFS */
    { "Limiter",       100,   5, 32846,      66 },

    /* 8: Surveillance — aggressive, keeps level constant for monitoring.
     *   target=-12dBFS, gate=-60dBFS */
    { "Surveillance",   95,  80, 16463,      66 },
};

/* I2S RX input timing delays (ESP8266 TRM §10.2.1.6, I2S.timing register).
 * Each delay is 0..3 (2 бита): задержка входного сэмпла в тактах APB
 * (12.5 нс при 80 МГц). Полезно для компенсации skew'а между INMP441
 * и BCK/WS на длинных проводах или при странном PCB-дизайне.
 *
 *   rx_sd_in_delay  — задержка сигнала DATA (SD) относительно BCK
 *   rx_ws_in_delay  — задержка сигнала WS  относительно BCK
 *   rx_bck_in_delay — задержка сигнала BCK
 *
 * Значение по умолчанию 0 (без задержки) подходит для INMP441
 * на коротких проводах. Настраивается через menuconfig или AT+TIMING.
 * Применяется при i2s_capture_init (после i2s_driver_install). */
#define I2S_TIMING_DELAY_MAX 3

#ifdef CONFIG_STREAMER_I2S_TIMING_SD_DELAY
#define I2S_TIMING_SD_DELAY_DEFAULT CONFIG_STREAMER_I2S_TIMING_SD_DELAY
#else
#define I2S_TIMING_SD_DELAY_DEFAULT 0
#endif

#ifdef CONFIG_STREAMER_I2S_TIMING_WS_DELAY
#define I2S_TIMING_WS_DELAY_DEFAULT CONFIG_STREAMER_I2S_TIMING_WS_DELAY
#else
#define I2S_TIMING_WS_DELAY_DEFAULT 0
#endif

#ifdef CONFIG_STREAMER_I2S_TIMING_BCK_DELAY
#define I2S_TIMING_BCK_DELAY_DEFAULT CONFIG_STREAMER_I2S_TIMING_BCK_DELAY
#else
#define I2S_TIMING_BCK_DELAY_DEFAULT 0
#endif

/* Transport mode — какой транспорт использовать для аудио-потока.
 *   0 = UDP: классический, datagram, без гарантий доставки/порядка.
 *   1 = TCP: ESP = listener (открывает listening socket), сервер подключается.
 *            Framing: [u16 length][pkt_header 16B][payload].
 *            TCP_NODELAY + неблокирующий send (drop при переполнении, как UDP).
 *   2 = Raw 802.11 TX: broadcast raw WiFi frames (monitor mode на приёмнике).
 * Применяется при AT+HOTRESTART. Диктуется ESP (как и каналы) — сервер
 * узнаёт тип из INFO payload. */
#define TRANSPORT_MODE_UDP    0
#define TRANSPORT_MODE_TCP    1
#define TRANSPORT_MODE_RAWTX  2

#ifdef CONFIG_STREAMER_TRANSPORT_MODE
#define TRANSPORT_MODE_DEFAULT CONFIG_STREAMER_TRANSPORT_MODE
#else
#define TRANSPORT_MODE_DEFAULT TRANSPORT_MODE_UDP
#endif

/* TCP transport tuning (only used when transport_mode == TRANSPORT_MODE_TCP).
 *   SEND_TIMEOUT_MS — таймаут блокирующего send(). При истечении соединение
 *     закрывается, accept task принимает новый connect.
 *     LAN: 1000-2000, плохой WiFi: 3000-5000.
 *   ACCEPT_TASK_STACK — стек фоновой задачи accept(). 1024 = минимум. */
#ifdef CONFIG_STREAMER_TCP_SEND_TIMEOUT_MS
#define TCP_SEND_TIMEOUT_MS CONFIG_STREAMER_TCP_SEND_TIMEOUT_MS
#else
#define TCP_SEND_TIMEOUT_MS 2000
#endif

#ifdef CONFIG_STREAMER_TCP_ACCEPT_TASK_STACK
#define TCP_ACCEPT_TASK_STACK CONFIG_STREAMER_TCP_ACCEPT_TASK_STACK
#else
#define TCP_ACCEPT_TASK_STACK 1024
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_TCP_ACCEPT
#define TCP_ACCEPT_TASK_PRIO CONFIG_STREAMER_TASK_PRIO_TCP_ACCEPT
#else
#define TCP_ACCEPT_TASK_PRIO 4
#endif

/* I2S communication format
 *   0 = Philips I2S (msb_shift=1) - standard, INMP441
 *   1 = LSB / Left-justified (msb_shift=0) */
#ifdef CONFIG_STREAMER_I2S_COMM_FORMAT
#define I2S_COMM_FORMAT_CFG CONFIG_STREAMER_I2S_COMM_FORMAT
#else
#define I2S_COMM_FORMAT_CFG 0
#endif

/* Frame duration (ms) - COMPUTED at runtime from sample_rate, channels, bits.
 * See i2s_capture_compute_frame_ms(). Guarantees:
 *   - samples_per_frame is even (ADPCM packs 2 samples/byte)
 *   - samples_per_frame/4 >= 32 (SDK DMA minimum)
 *   - UDP packet <= 1400 bytes (MTU safe, codec & bits aware)
 *   - If transport_mode == RawTX: air_time/sec <= 0.95 (throughput limit) */
uint32_t i2s_capture_compute_frame_ms(uint32_t sample_rate, int channels,
                                       int codec_mode, int bits_per_sample);

/* Number of audio channels - configured via Kconfig
 *   1 = mono, 2 = stereo */
#ifdef CONFIG_STREAMER_AUDIO_CHANNELS
#define AUDIO_CHANNELS      CONFIG_STREAMER_AUDIO_CHANNELS
#else
#define AUDIO_CHANNELS      1
#endif

/* I2S channel format (matches ESP8266 RTOS SDK enum)
 *   0 = I2S_CHANNEL_FMT_RIGHT_LEFT  (stereo)
 *   1 = I2S_CHANNEL_FMT_ALL_RIGHT
 *   2 = I2S_CHANNEL_FMT_ALL_LEFT
 *   3 = I2S_CHANNEL_FMT_ONLY_RIGHT  (mono right)
 *   4 = I2S_CHANNEL_FMT_ONLY_LEFT   (mono left) */
#ifdef CONFIG_STREAMER_I2S_CHANNEL_FORMAT
#define I2S_CHANNEL_FORMAT  CONFIG_STREAMER_I2S_CHANNEL_FORMAT
#else
#define I2S_CHANNEL_FORMAT  4   /* ONLY_LEFT */
#endif

/* ADPCM = 4 bits/sample x channels */
#define AUDIO_BITRATE       (AUDIO_SAMPLE_RATE * 4 * AUDIO_CHANNELS)
#define CODEC_ID_ADPCM      5       /* DVI4 IMA ADPCM */
#define CODEC_ID_PCM        6       /* Raw 16/24-bit signed PCM */

/* Audio codec selection (0 = ADPCM, 1 = PCM).
 * ADPCM: 4 bits/sample, low bandwidth (32 kbps @ 16kHz).
 *        Requires encoding, but only ~10% CPU on ESP8266.
 * PCM:   Raw 16-bit or 24-bit signed PCM, no compression.
 *        High bandwidth (1536 kbps @ 48kHz/16-bit/stereo).
 *        Zero CPU overhead for encoding, but exceeds UDP MTU at
 *        high sample rates - frame_ms is auto-reduced to fit.
 * Adjustable at runtime via AT+CODEC=0|1 (saved, applies on next stream). */
#define CODEC_MODE_ADPCM    0
#define CODEC_MODE_PCM      1

#ifdef CONFIG_STREAMER_AUDIO_CODEC
#define AUDIO_CODEC_DEFAULT CONFIG_STREAMER_AUDIO_CODEC
#else
#define AUDIO_CODEC_DEFAULT CODEC_MODE_ADPCM
#endif

/* WiFi channel for Raw 802.11 TX mode (used when transport_mode == TRANSPORT_MODE_RAWTX).
 * Configurable via menuconfig (STREAMER_RAWTX_CHANNEL) or AT+WCH=1..13. */
#ifdef CONFIG_STREAMER_RAWTX_CHANNEL
#define RAWTX_CHANNEL_DEFAULT CONFIG_STREAMER_RAWTX_CHANNEL
#else
#define RAWTX_CHANNEL_DEFAULT 1
#endif

/* Firmware version - single source of truth.
 * Must match the protocol version implemented:
 *   v2.0 = INFO payload 34 bytes (no transport_mode, no hostname)
 *   v2.1 = +1 byte transport_mode (35 bytes)
 *   v2.2 = +24 bytes hostname (58 bytes)  <-- current
 * The receiver reads the fixed 58-byte v2.2 INFO payload regardless of this
 * string, but reporting the correct version lets the UI show accurate info
 * and avoids confusion when debugging protocol mismatches. */
#define FIRMWARE_VERSION    "v2.2"

/* samples_per_frame and adpcm_frame_bytes are computed at runtime in
 * start_streaming() from frame_ms - no compile-time constants. */

/* ====================================================================
 *  WiFi defaults - configured via Kconfig, overridable via AT+WIFI
 * ==================================================================== */

#ifdef CONFIG_STREAMER_WIFI_SSID
#define WIFI_SSID_DEFAULT        CONFIG_STREAMER_WIFI_SSID
#else
#define WIFI_SSID_DEFAULT        "YOUR_WIFI_SSID"
#endif

#ifdef CONFIG_STREAMER_WIFI_PASSWORD
#define WIFI_PASSWORD_DEFAULT    CONFIG_STREAMER_WIFI_PASSWORD
#else
#define WIFI_PASSWORD_DEFAULT    "12345678"
#endif

#ifdef CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#define WIFI_TX_POWER_DEFAULT    CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#define WIFI_TX_POWER_MAX        CONFIG_ESP8266_PHY_MAX_WIFI_TX_POWER
#else
#define WIFI_TX_POWER_DEFAULT    20
#define WIFI_TX_POWER_MAX        20
#endif
#define WIFI_TX_POWER_MIN        0

#ifdef CONFIG_STREAMER_WIFI_HOSTNAME
#define WIFI_HOSTNAME_DEFAULT    CONFIG_STREAMER_WIFI_HOSTNAME
#else
#define WIFI_HOSTNAME_DEFAULT    "esp-streamer"
#endif

#ifdef CONFIG_STREAMER_WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS  CONFIG_STREAMER_WIFI_CONNECT_TIMEOUT_MS
#else
#define WIFI_CONNECT_TIMEOUT_MS  15000
#endif

#ifdef CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MIN_MS
#define WIFI_RECONNECT_BACKOFF_MIN_MS  CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MIN_MS
#else
#define WIFI_RECONNECT_BACKOFF_MIN_MS  1000
#endif

#ifdef CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MAX_MS
#define WIFI_RECONNECT_BACKOFF_MAX_MS  CONFIG_STREAMER_WIFI_RECONNECT_BACKOFF_MAX_MS
#else
#define WIFI_RECONNECT_BACKOFF_MAX_MS  15000
#endif

/* Raw 802.11 TX mode: how long to wait for WIFI_EVENT_STA_START after
 * esp_wifi_start() before giving up. esp_wifi_start() is asynchronous - it
 * returns before the radio is actually up; we block on the STA_START event
 * (posted by the WiFi driver once the radio is calibrated) so the first
 * esp_wifi_80211_tx() call succeeds instead of being dropped. Typical
 * bring-up is ~100-300 ms; 3 s is a safety net for a wedged radio. */
#ifdef CONFIG_STREAMER_WIFI_RAW_START_TIMEOUT_MS
#define WIFI_RAW_START_TIMEOUT_MS  CONFIG_STREAMER_WIFI_RAW_START_TIMEOUT_MS
#else
#define WIFI_RAW_START_TIMEOUT_MS  3000
#endif

/* ====================================================================
 *  Service Port (EASSP) - configured via Kconfig
 * ==================================================================== */

#ifdef CONFIG_STREAMER_SVC_PORT
#define SVC_PORT_DEFAULT         CONFIG_STREAMER_SVC_PORT
#else
#define SVC_PORT_DEFAULT         3950
#endif

#ifdef CONFIG_STREAMER_SVC_WATCHDOG_TIMEOUT_MS
#define SVC_WATCHDOG_TIMEOUT_MS  CONFIG_STREAMER_SVC_WATCHDOG_TIMEOUT_MS
#else
#define SVC_WATCHDOG_TIMEOUT_MS  15000
#endif

#ifdef CONFIG_STREAMER_SVC_INFO_INTERVAL_MS
#define SVC_INFO_INTERVAL_MS     CONFIG_STREAMER_SVC_INFO_INTERVAL_MS
#else
#define SVC_INFO_INTERVAL_MS     1000
#endif

/* Broadcast announcements - controlled by Kconfig STREAMER_SVC_ANNOUNCE_ENABLED. */
#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_ENABLED
#define SVC_ANNOUNCE_ENABLED     1
#else
#define SVC_ANNOUNCE_ENABLED     0
#endif

#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_MIN_MS
#define SVC_ANNOUNCE_MIN_MS      CONFIG_STREAMER_SVC_ANNOUNCE_MIN_MS
#else
#define SVC_ANNOUNCE_MIN_MS      1000
#endif

#ifdef CONFIG_STREAMER_SVC_ANNOUNCE_MAX_MS
#define SVC_ANNOUNCE_MAX_MS      CONFIG_STREAMER_SVC_ANNOUNCE_MAX_MS
#else
#define SVC_ANNOUNCE_MAX_MS      5000
#endif

#ifdef CONFIG_STREAMER_SVC_RECV_BUF_SIZE
#define SVC_RECV_BUF_SIZE        CONFIG_STREAMER_SVC_RECV_BUF_SIZE
#else
#define SVC_RECV_BUF_SIZE        256
#endif

#ifdef CONFIG_STREAMER_SVC_RECONFIGURE_STOP_TIMEOUT_MS
#define SVC_RECONFIGURE_STOP_TIMEOUT_MS  CONFIG_STREAMER_SVC_RECONFIGURE_STOP_TIMEOUT_MS
#else
#define SVC_RECONFIGURE_STOP_TIMEOUT_MS  2000
#endif

/* ====================================================================
 *  Pipeline / Task Configuration
 * ==================================================================== */

#ifdef CONFIG_STREAMER_TASK_PRIO_I2S
#define TASK_PRIO_I2S       CONFIG_STREAMER_TASK_PRIO_I2S
#else
#define TASK_PRIO_I2S       5
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_ADPCM
#define TASK_PRIO_ADPCM     CONFIG_STREAMER_TASK_PRIO_ADPCM
#else
#define TASK_PRIO_ADPCM     3
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_UDP
#define TASK_PRIO_UDP       CONFIG_STREAMER_TASK_PRIO_UDP
#else
#define TASK_PRIO_UDP       2
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_AT
#define TASK_PRIO_AT        CONFIG_STREAMER_TASK_PRIO_AT
#else
#define TASK_PRIO_AT        1
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_SVC
#define TASK_PRIO_SVC       CONFIG_STREAMER_TASK_PRIO_SVC
#else
#define TASK_PRIO_SVC       2
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_I2S
#define TASK_STACK_I2S      CONFIG_STREAMER_TASK_STACK_I2S
#else
#define TASK_STACK_I2S      3584
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_ADPCM
#define TASK_STACK_ADPCM    CONFIG_STREAMER_TASK_STACK_ADPCM
#else
#define TASK_STACK_ADPCM    2560
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_UDP
#define TASK_STACK_UDP      CONFIG_STREAMER_TASK_STACK_UDP
#else
#define TASK_STACK_UDP      3072
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_AT
#define TASK_STACK_AT       CONFIG_STREAMER_TASK_STACK_AT
#else
#define TASK_STACK_AT       3584
#endif

#ifdef CONFIG_STREAMER_TASK_STACK_SVC
#define TASK_STACK_SVC      CONFIG_STREAMER_TASK_STACK_SVC
#else
#define TASK_STACK_SVC      3584
#endif

/* ---- Supervisor task ---- */
#ifdef CONFIG_STREAMER_TASK_STACK_SUPERVISOR
#define TASK_STACK_SUPERVISOR  CONFIG_STREAMER_TASK_STACK_SUPERVISOR
#else
#define TASK_STACK_SUPERVISOR  2048
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_SUPERVISOR
#define TASK_PRIO_SUPERVISOR   CONFIG_STREAMER_TASK_PRIO_SUPERVISOR
#else
#define TASK_PRIO_SUPERVISOR   1
#endif

#ifdef CONFIG_STREAMER_SUPERVISOR_MIN_HEAP
#define SUPERVISOR_MIN_HEAP_BYTES   CONFIG_STREAMER_SUPERVISOR_MIN_HEAP
#else
#define SUPERVISOR_MIN_HEAP_BYTES   15360
#endif

#ifdef CONFIG_STREAMER_SUPERVISOR_STALL_TIMEOUT
#define SUPERVISOR_STALL_TIMEOUT_MS CONFIG_STREAMER_SUPERVISOR_STALL_TIMEOUT
#else
#define SUPERVISOR_STALL_TIMEOUT_MS 15000
#endif

#ifdef CONFIG_STREAMER_SUPERVISOR_MIN_STACK
#define SUPERVISOR_MIN_STACK_BYTES  CONFIG_STREAMER_SUPERVISOR_MIN_STACK
#else
#define SUPERVISOR_MIN_STACK_BYTES  256
#endif

#ifdef CONFIG_STREAMER_SUPERVISOR_CHECK_INTERVAL
#define SUPERVISOR_CHECK_INTERVAL_MS CONFIG_STREAMER_SUPERVISOR_CHECK_INTERVAL
#else
#define SUPERVISOR_CHECK_INTERVAL_MS 2000
#endif

/* ---- TCP socket options ----
 * NOTE: macro names use CFG_ prefix to avoid collisions with lwIP
 * socket option constants (TCP_NODELAY, TCP_KEEPIDLE, TCP_KEEPINTVL,
 * TCP_KEEPCNT are all defined in lwIP/sockets.h). */
#ifdef CONFIG_STREAMER_TCP_NODELAY_ENABLED
#define CFG_TCP_NODELAY_ENABLED    1
#else
#define CFG_TCP_NODELAY_ENABLED    0
#endif

/* ---- TCP keepalive ---- */
#ifdef CONFIG_STREAMER_TCP_KEEPALIVE_ENABLED
#define CFG_TCP_KEEPALIVE_ENABLED  1
#else
#define CFG_TCP_KEEPALIVE_ENABLED  0
#endif

#ifdef CONFIG_STREAMER_TCP_KEEPIDLE
#define CFG_TCP_KEEPIDLE_SEC       CONFIG_STREAMER_TCP_KEEPIDLE
#else
#define CFG_TCP_KEEPIDLE_SEC       10
#endif

#ifdef CONFIG_STREAMER_TCP_KEEPINTVL
#define CFG_TCP_KEEPINTVL_SEC      CONFIG_STREAMER_TCP_KEEPINTVL
#else
#define CFG_TCP_KEEPINTVL_SEC      3
#endif

#ifdef CONFIG_STREAMER_TCP_KEEPCNT
#define CFG_TCP_KEEPCNT            CONFIG_STREAMER_TCP_KEEPCNT
#else
#define CFG_TCP_KEEPCNT            3
#endif

#ifdef CONFIG_STREAMER_TCP_LINGER_ENABLED
#define CFG_TCP_LINGER_ENABLED     1
#else
#define CFG_TCP_LINGER_ENABLED     0
#endif

/* ---- Supervisor task ----
 * Software watchdog that monitors heap, pipeline liveness, and stack
 * health. Runs independently of the streaming pipeline. If any check
 * fails, calls esp_restart() immediately. See supervisor_task_fn in
 * main.c for details. */
#ifdef CONFIG_STREAMER_TASK_STACK_SUPERVISOR
#define TASK_STACK_SUPERVISOR  CONFIG_STREAMER_TASK_STACK_SUPERVISOR
#else
#define TASK_STACK_SUPERVISOR  2048
#endif

#ifdef CONFIG_STREAMER_TASK_PRIO_SUPERVISOR
#define TASK_PRIO_SUPERVISOR   CONFIG_STREAMER_TASK_PRIO_SUPERVISOR
#else
#define TASK_PRIO_SUPERVISOR   1    /* low prio — runs when system is idle */
#endif

/* (Heap threshold, stall timeout, stack threshold, and check interval are
 *  defined above via CONFIG_STREAMER_SUPERVISOR_* macros — see lines ~538-560.
 *  Do NOT redefine them here.) */

/* PCM/ADPCM pool sizes are computed at runtime in start_streaming() from
 * free heap and frame_ms - see main.c. No compile-time setting needed. */

/* FIX (split): separate stop timeouts for UDP and TCP. Previously a single
 * STREAM_STOP_TIMEOUT_MS was used for both, but UDP and TCP have different
 * send timeouts (UDP_SEND_TIMEOUT_MS, TCP_SEND_TIMEOUT_MS), and the stop
 * timeout must be > the corresponding send timeout. Splitting lets the user
 * tune each transport independently. */
#ifdef CONFIG_STREAMER_STREAM_STOP_TIMEOUT_UDP_MS
#define STREAM_STOP_TIMEOUT_UDP_MS  CONFIG_STREAMER_STREAM_STOP_TIMEOUT_UDP_MS
#else
/* Default if Kconfig is not included: must be > UDP_SEND_TIMEOUT_MS (2000). */
#define STREAM_STOP_TIMEOUT_UDP_MS  3000
#endif

#ifdef CONFIG_STREAMER_STREAM_STOP_TIMEOUT_TCP_MS
#define STREAM_STOP_TIMEOUT_TCP_MS  CONFIG_STREAMER_STREAM_STOP_TIMEOUT_TCP_MS
#else
/* Default if Kconfig is not included: must be > TCP_SEND_TIMEOUT_MS (2000). */
#define STREAM_STOP_TIMEOUT_TCP_MS  3000
#endif

/* Legacy alias for code that hasn't been updated to use the transport-
 * specific variant. Uses the max of UDP/TCP so the wait always covers the
 * worst case. New code should use STREAM_STOP_TIMEOUT_UDP_MS or
 * STREAM_STOP_TIMEOUT_TCP_MS directly. */
#define STREAM_STOP_TIMEOUT_MS  \
    (STREAM_STOP_TIMEOUT_UDP_MS > STREAM_STOP_TIMEOUT_TCP_MS ? \
     STREAM_STOP_TIMEOUT_UDP_MS : STREAM_STOP_TIMEOUT_TCP_MS)

/* FIX (M31): cross-validation checks moved to END of this file (after all
 * timeout macros are defined). Earlier placement here caused #error to
 * fire on undefined UDP_SEND_TIMEOUT_MS / BATT_* macros (treated as 0 by
 * the preprocessor). See "Cross-validation checks" section near EOF. */

/* FIX (M32): see M31 — battery threshold cross-check moved to EOF. */

/* I2S DMA buffer dimensions are DERIVED from samples_per_frame at runtime
 * (see i2s_capture_init). One PCM frame = 4 DMA buffers, so each DMA
 * buffer fills in frame_ms/4. DMA buffer count gives ~256ms of headroom. */

/* ====================================================================
 *  AT Command Interface
 * ==================================================================== */

#ifdef CONFIG_STREAMER_AT_CMD_ENABLED
#define AT_CMD_ENABLED      1
#else
#define AT_CMD_ENABLED      0
#endif

#ifdef CONFIG_STREAMER_UART_BAUD_RATE
#define UART_BAUD_RATE      CONFIG_STREAMER_UART_BAUD_RATE
#else
#define UART_BAUD_RATE      115200
#endif

/* ====================================================================
 *  Network / UDP
 * ==================================================================== */

#ifdef CONFIG_STREAMER_UDP_SEND_TIMEOUT_MS
#define UDP_SEND_TIMEOUT_MS CONFIG_STREAMER_UDP_SEND_TIMEOUT_MS
#else
#define UDP_SEND_TIMEOUT_MS 2000
#endif

/* ====================================================================
 *  Battery Monitoring (optional, ported from ESP8285-WEBSERVER project)
 * ====================================================================
 *
 * ESP8266 has a single ADC channel (TOUT pin, ADC_READ_TOUT_MODE) which
 * measures 0-1V (10-bit, 0-1023). A voltage divider on the battery side
 * scales V_batt down to fit this 0-1V range.
 *
 * Example divider for Li-Ion (3.0-4.2V):
 *   R1=100k (to V_batt), R2=33k (to GND), TOUT at junction
 *   V_tout = V_batt * R2 / (R1 + R2) = V_batt * 33/133 = V_batt * 0.2481
 *   At V_batt=4.2V -> V_tout=1.042V (slightly clipped, OK)
 *   At V_batt=3.0V -> V_tout=0.744V
 *   RATIO = 1024 / 0.2481 ~ 5711 (calibration constant)
 *
 * Formula: V_batt_mV = (ADC_raw x RATIO) / 1024
 *
 * IMPORTANT: ESP8266 ADC is SHARED - if the I2S INMP441 mic uses GPIO12
 * (data), the ADC TOUT pin (separate from GPIOs) remains available.
 * Verify that your hardware routes V_batt divider to the TOUT pin, not
 * to a GPIO used by I2S.
 */

#ifdef CONFIG_STREAMER_BATTERY_ENABLED
#define BATTERY_ENABLED 1
#else
#define BATTERY_ENABLED 0
#endif

#ifndef CONFIG_STREAMER_BATT_CRITICAL_MV
#define BATT_CRITICAL_MV  3700   /* below -> deep sleep */
#else
#define BATT_CRITICAL_MV  CONFIG_STREAMER_BATT_CRITICAL_MV
#endif

#ifndef CONFIG_STREAMER_BATT_START_MV
#define BATT_START_MV     3900   /* below on boot -> don't start */
#else
#define BATT_START_MV     CONFIG_STREAMER_BATT_START_MV
#endif

#ifndef CONFIG_STREAMER_BATT_BAD_MV
#define BATT_BAD_MV       2500   /* below -> reading is invalid */
#else
#define BATT_BAD_MV       CONFIG_STREAMER_BATT_BAD_MV
#endif

#ifndef CONFIG_STREAMER_BATT_DIVIDER_RATIO
#define BATT_DIVIDER_RATIO 5711  /* R1=100k, R2=33k -> 5711 */
#else
#define BATT_DIVIDER_RATIO CONFIG_STREAMER_BATT_DIVIDER_RATIO
#endif

#ifndef CONFIG_STREAMER_BATT_ADC_SAMPLES
#define BATT_ADC_SAMPLES  15
#else
#define BATT_ADC_SAMPLES  CONFIG_STREAMER_BATT_ADC_SAMPLES
#endif

#ifndef CONFIG_STREAMER_BATT_ADC_DELAY_MS
#define BATT_ADC_DELAY_MS 50
#else
#define BATT_ADC_DELAY_MS CONFIG_STREAMER_BATT_ADC_DELAY_MS
#endif

#ifndef CONFIG_STREAMER_BATT_CHECK_MIN
#define BATT_CHECK_MIN    1      /* check every N minutes during operation */
#else
#define BATT_CHECK_MIN    CONFIG_STREAMER_BATT_CHECK_MIN
#endif

#ifndef CONFIG_STREAMER_BATT_SLEEP_MIN
#define BATT_SLEEP_MIN    30     /* deep sleep duration on critical battery */
#else
#define BATT_SLEEP_MIN    CONFIG_STREAMER_BATT_SLEEP_MIN
#endif

#ifndef CONFIG_STREAMER_BATT_TASK_STACK
#define BATT_TASK_STACK   1024
#else
#define BATT_TASK_STACK   CONFIG_STREAMER_BATT_TASK_STACK
#endif

#ifndef CONFIG_STREAMER_BATT_TASK_PRIO
#define BATT_TASK_PRIO    3
#else
#define BATT_TASK_PRIO    CONFIG_STREAMER_BATT_TASK_PRIO
#endif

/* ====================================================================
 *  Fixed Protocol Constants (NOT configurable)
 * ==================================================================== */

/*
 * UDP packet header (16 bytes, packed):
 *   seq_num(2) + timestamp_ms(4) + codec(1) +
 *   sample_rate_enum(1) + channels(1) + frame_ms(1) +
 *   bitrate(4) + flags(2)
 */
#define PKT_HDR_SIZE        16
#define DVI4_HEADER_SIZE    4        /* predict(2) + index(1) + reserved(1) */

/* ====================================================================
 *  Cross-validation checks (M31, M32)
 * ====================================================================
 * FIX (M31/M32): these checks MUST live at the END of this file, AFTER all
 * the macros they reference have been defined. Earlier placement (right
 * after STREAM_STOP_TIMEOUT_MS) caused #error to fire on still-undefined
 * UDP_SEND_TIMEOUT_MS / BATT_* macros (the C preprocessor treats undefined
 * identifiers as 0 in #if expressions, so "0 <= 0" was always true).
 *
 * Now all macros are defined above, so these checks fire only when the
 * actual user-configured values violate the invariants. */

/* M31: STREAM_STOP_TIMEOUT_*_MS must be > corresponding send timeout,
 * otherwise a task blocked in sendto()/send() could be force-deleted by
 * stop_streaming() while still inside lwIP -> orphaned mutex ->
 * deadlock on next start_streaming(). */
#if (STREAM_STOP_TIMEOUT_UDP_MS <= UDP_SEND_TIMEOUT_MS)
#error "STREAM_STOP_TIMEOUT_UDP_MS must be > UDP_SEND_TIMEOUT_MS (force-deleting a task blocked in sendto() corrupts lwIP state)"
#endif
#if (STREAM_STOP_TIMEOUT_TCP_MS <= TCP_SEND_TIMEOUT_MS)
#error "STREAM_STOP_TIMEOUT_TCP_MS must be > TCP_SEND_TIMEOUT_MS (force-deleting a task blocked in send() corrupts lwIP state)"
#endif

/* M32: BATT_START_MV must be > BATT_CRITICAL_MV, otherwise the boot check
 * is inverted (start threshold below deep-sleep threshold — the device
 * would deep-sleep at boot with a battery that's considered OK during run). */
#if BATTERY_ENABLED
#if (BATT_START_MV <= BATT_CRITICAL_MV)
#error "BATT_START_MV must be > BATT_CRITICAL_MV (boot deep-sleep threshold inverted)"
#endif
/* FIX (AUDIT-H19): battery_get_percent() in battery.c computes
 * (4200U - BATT_CRITICAL_MV) as the denominator for linear interpolation.
 * If BATT_CRITICAL_MV >= 4200, the unsigned subtraction underflows to
 * ~4.29 billion and battery_get_percent() always returns 0 even with a
 * full battery. Fail the build instead. 4200 mV is the standard Li-Ion
 * full-charge voltage; if a different chemistry is used, update both
 * this guard and battery_get_percent(). */
#if (BATT_CRITICAL_MV >= 4200)
#error "BATT_CRITICAL_MV must be < 4200 (full Li-Ion mV) - battery_get_percent() would underflow"
#endif
#endif


#endif /* BOARD_CONFIG_H */
